
version: "3"

services:
  wireguard:
    image: root0x/wireguard
    volumes:
      - /lib/modules:/lib/modules
      - /opt/wireguard:/root/clients
    sysctls:
      - "net.ipv4.conf.all.rp_filter=2"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - HOST=209.97.187.87:443
    ports:
      - "443:51820/udp"
    restart: always
    container_name: wireguard
